# Generated by Django 2.0.8 on 2019-04-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20190425_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.IntegerField(default=0),
        ),
    ]
