# Generated by Django 2.0.8 on 2019-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_task_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
